name: CD
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Create new tag
        id: create_tag
        run: |
          git fetch --tags
          tag=$(git tag | tail -1 | awk -F. '{$NF++; print}' OFS='.')
          echo "NEW_TAG=$tag" >> $GITHUB_ENV

      - name: Update package.json
        run: |
          npm version ${NEW_TAG} --no-git-tag-version
          git commit -am "Bump version to ${NEW_TAG}"
          git tag "v${NEW_TAG}"
          git push && git push --tags

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}