name: CICD
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      # - name: Install deps and build (with cache)
      #   uses: bahmutov/npm-install@v1

      # - name: Lint
      #   run: npm run lint
      - name: Install deps
        run: npm install

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

